### ISSUE TITLE
Android build seems to be broken since 5.0.0

### ISSUE THREAD

**Issue by Nightbr** [ionic-team/cordova-plugin-ionic#102]
Hey,

since 3 days (the release of 5.0.0) it seems Android build is broken. 
It was working last week. Build failed in local build and ionic pro package.

`BUILD FAILED in 1m 52s 32 actionable tasks: 32 executed (node:1) UnhandledPromiseRejectionWarning: Error: /usr/src/app/platforms/android/gradlew: Command failed with exit code 1 Error output: Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. /usr/src/app/platforms/android/src/com/ionicframework/common/IonicCordovaCommon.java:72: error: strings in switch are not supported in -source 1.6 switch(action) { ^ (use -source 7 or higher to enable strings in switch) /usr/src/app/platforms/android/src/com/ionicframework/common/IonicCordovaCommon.java:144: error: cannot find symbol SharedPreferences prefs = this.cordova.getContext().getSharedPreferences("com.ionic.deploy.preferences", Context.MODE_PRIVATE); ^ symbol: method getContext() location: variable cordova of type CordovaInterface /usr/src/app/platforms/android/src/com/ionicframework/common/IonicCordovaCommon.java:201: error: cannot find symbol SharedPreferences prefs = this.cordova.getContext().getSharedPreferences("com.ionic.deploy.preferences", Context.MODE_PRIVATE); ^ symbol: method getContext() location: variable cordova of type CordovaInterface Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: /usr/src/app/platforms/android/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details. 3 errors FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':compileReleaseJavaWithJavac'. > Compilation failed; see the compiler error output for details.`

It seems to come from this plugin.

Don't hesitate to ask if you need some other logs or debug.

Thanks!

**Comment by nphyatt** [comment]
Thanks for the report @Nightbr can you show me the output for `cordova plugin ls`?

**Comment by Nightbr** [comment]
```
$ cordova plugin ls
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-fullscreen 1.1.0 "cordova-plugin-fullscreen"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic 4.2.0 "IonicCordova"
cordova-plugin-ionic-webview 2.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```
Humm... seems to still be in 4.2.0

I will dig this deeper tomorrow! (force update to 5.0.0 and rebuild).

**Comment by nphyatt** [comment]
Yeah I think that version `4.2.0` has some syntax that doesn't agree with older versions of the Java Runtime so if you're running an older verision of Java on your machine that'd be the issue. If you can I'd recommend upgrading the version `5.x.x` as that shouldn't have the issue and will be receiving faster updates and bug fixes.

**Comment by chrisvanderkooi** [comment]
Hi @nphyatt 

So you're saying, first, update Java and then secondly, update `cordova-plugin-ionic` to `5.0.0`?

I have a similar problem to Nightbr.

**Comment by nphyatt** [comment]
@chrisvanderkooi if you upgrade to `5.0.0` you shouldn’t need to update java. We’ve released a fix for that to support older versions of java. I might try to get the fix into v4 as well but it might take a little longer as I’m currently focusing on triaging issues with v5 as they come in.

**Comment by chrisvanderkooi** [comment]
@nphyatt just an fyi, I upgraded `cordova-plugin-ionic` to `5.0.0` but I still cannot seem to do a local android build. Same errors:
```
BUILD FAILED in 18s
39 actionable tasks: 39 executed
Error: /Websites/ccdex/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/chrisv/.gradle/caches/transforms-1/files-1.1/firebase-iid-16.2.0.aar/b603d65ba3d5865eaa66240d08090b1e/jars/classes.jar(com/google/firebase/iid/FirebaseInstanceId.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy': class file for javax.annotation.concurrent.GuardedBy not found
/Users/chrisv/.gradle/caches/transforms-1/files-1.1/firebase-iid-16.2.0.aar/b603d65ba3d5865eaa66240d08090b1e/jars/classes.jar(com/google/firebase/iid/FirebaseInstanceId.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
/Users/chrisv/.gradle/caches/transforms-1/files-1.1/firebase-iid-16.2.0.aar/b603d65ba3d5865eaa66240d08090b1e/jars/classes.jar(com/google/firebase/iid/FirebaseInstanceId.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
/Websites/ccdex/platforms/android/src/com/ionicframework/common/IonicCordovaCommon.java:139: error: cannot find symbol
    SharedPreferences prefs = this.cordova.getContext().getSharedPreferences("com.ionic.deploy.preferences", Context.MODE_PRIVATE);
                                          ^
  symbol:   method getContext()
  location: variable cordova of type CordovaInterface
/Websites/ccdex/platforms/android/src/com/ionicframework/common/IonicCordovaCommon.java:196: error: cannot find symbol
    SharedPreferences prefs = this.cordova.getContext().getSharedPreferences("com.ionic.deploy.preferences", Context.MODE_PRIVATE);
                                          ^
  symbol:   method getContext()
  location: variable cordova of type CordovaInterface
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
3 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
```

For your information, here are my packages:
```
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic 5.0.0-rc.3 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
```
and here is my ionic info:
```
Ionic:

   ionic (Ionic CLI)  : 4.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.8.0
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.4.0

System:

   ios-deploy : 1.9.2
   ios-sim    : 5.0.6
   NodeJS     : v8.9.1 (/usr/local/bin/node)
   npm        : 6.1.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : not set
```

**Comment by nphyatt** [comment]
@chrisvanderkooi looks like it solve one of the issues...can you tell me the output for `java --version`?

**Comment by chrisvanderkooi** [comment]
@nphyatt 
```
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

**Comment by nphyatt** [comment]
Great thanks @chrisvanderkooi! 

Looks like some of the methods we were using were only available in `cordova-android@>=7.0.0` so `6.4.0` was failing to compile. I just updated the methods and released `cordova-plugin-ionic@5.0.2` so it should be compatible now would you mind trying again @chrisvanderkooi and @Nightbr ?

**Comment by chrisvanderkooi** [comment]
@nphyatt Great news, it worked!
```
BUILD SUCCESSFUL in 16s
```
Thanks for all your help. 👍

**Comment by Nightbr** [comment]
@nphyatt GJ! Thanks for your reactivity and your help!

```
BUILD SUCCESSFUL in 16s
44 actionable tasks: 44 executed
```

Cheers!

**Comment by khalilchoudhry** [comment]
I do not have cordova-plugin-ionic in my plugins list and still have this issue. Cannot figure out what the problem is. Please guide

**Comment by khalilchoudhry** [comment]
I do not have cordova-plugin-ionic in my plugins list and still have this issue. Cannot figure out what the problem is.
