### ISSUE TITLE
Ionic Pro Build Package ENOENT: no such file or directory, open '/usr/src/app/plugins/cordova-plugin-ionic/dist/common.js'

### ISSUE THREAD

**Issue by ChampRay** [ionic-team/cordova-plugin-ionic#181]
Works locally, when being built as a package on Ionic Pro, I get this.
**cordova plugin ls output:**
```
Android project created with cordova-android@6.4.0
Installing "cordova-plugin-autostart" for android
Installing "cordova-plugin-background-mode" for android
Plugin dependency "cordova-plugin-device@2.0.2" already fetched, using that version.
Installing "cordova-plugin-device" for android
Installing "cordova-plugin-bluetooth-serial" for android
Plugin "cordova-plugin-device" already installed on android. Making it top-level.
Installing "cordova-plugin-file" for android

The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      ""

to config.xml in order for the application to find previously stored files.
        
Installing "cordova-plugin-file-transfer" for android
Plugin dependency "cordova-plugin-file@6.0.1" already fetched, using that version.
Dependent plugin "cordova-plugin-file" already installed on android.
Installing "cordova-plugin-ionic" for android
Plugin dependency "cordova-plugin-splashscreen@5.0.2" already fetched, using that version.
Installing "cordova-plugin-splashscreen" for android
Plugin dependency "cordova-plugin-ionic-webview@2.2.0" already fetched, using that version.
Installing "cordova-plugin-ionic-webview" for android
Subproject Path: CordovaLib
Plugin dependency "cordova-plugin-file@6.0.1" already fetched, using that version.
Dependent plugin "cordova-plugin-file" already installed on android.
Plugin dependency "cordova-plugin-file-transfer@1.7.1" already fetched, using that version.
Dependent plugin "cordova-plugin-file-transfer" already installed on android.
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-ionic': Error: Uh oh!
ENOENT: no such file or directory, open '/usr/src/app/plugins/cordova-plugin-ionic/dist/common.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at install (/usr/src/app/platforms/android/cordova/lib/pluginHandlers.js:173:36)
    at ActionStack.process (/usr/src/app/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/usr/src/app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/usr/src/app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /usr/src/app/platforms/android/cordova/Api.js:243:74
    at _fulfilled (/usr/src/app/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/usr/src/app/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/usr/src/app/platforms/android/cordova/node_modules/q/q.js:816:13)
(node:1) UnhandledPromiseRejectionWarning: Error: Uh oh!
ENOENT: no such file or directory, open '/usr/src/app/plugins/cordova-plugin-ionic/dist/common.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at install (/usr/src/app/platforms/android/cordova/lib/pluginHandlers.js:173:36)
    at ActionStack.process (/usr/src/app/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/usr/src/app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/usr/src/app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /usr/src/app/platforms/android/cordova/Api.js:243:74
    at _fulfilled (/usr/src/app/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/usr/src/app/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/usr/src/app/platforms/android/cordova/node_modules/q/q.js:816:13)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**ionic info output:**
```
Ionic:

   ionic (Ionic CLI)  : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : cordova-plugin-ionic 5.2.6, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 11 other plugins)

System:

   NodeJS : v8.11.1 (/usr/local/bin/node)
   npm    : 5.10.0
   OS     : Linux 4.4
```

**Describe the bug**
I get a error that corrupts my APK when building a package on Ionic Pro implementing the Deploy code, including the cordova-plugin-ionic plugin.

**To Reproduce**
1. Add Ionic Pro Deploy / Live updates to your project.
2. Try to build a package using a new Ionic Pro Package, Android / Release
3. Cordova-plugin-ionic fails package.

Package.json:
```
 "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/bluetooth-serial": "^4.16.0",
    "@ionic-native/core": "^4.16.0",
    "@ionic-native/device": "^4.16.0",
    "@ionic-native/diagnostic": "^4.16.0",
    "@ionic-native/native-audio": "^4.16.0",
    "@ionic-native/splash-screen": "^4.16.0",
    "@ionic-native/status-bar": "^4.16.0",
    "@ionic/pro": "^2.0.3",
    "@ionic/storage": "2.2.0",
    "cordova-android": "6.4.0",
    "cordova-plugin-autostart": "git+https://github.com/ToniKorin/cordova-plugin-autostart.git",
    "cordova-plugin-background-mode": "git+https://github.com/katzer/cordova-plugin-background-mode.git",
    "cordova-plugin-bluetooth-serial": "^0.4.7",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-ionic": "^5.2.6",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^2.2.0",
    "cordova-plugin-nativeaudio": "^3.0.9",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova.plugins.diagnostic": "^4.0.10",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "pusher-js": "^4.3.1",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
```

**Comment by jcesarmobile** [comment]
can you also share your config.xml?

**Comment by ChampRay** [comment]
`
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.ionicframework.*******388321" version="1.88" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>*******</name>
    <description>*********</description>
    <author email="*******" href="http:/*******/">*****</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-navigation href="http://localhost/*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="19" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="loadUrlTimeoutValue" value="700000" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <platform name="android">
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
    </platform>
    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-statusbar" spec="2.4.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="^2.0.0" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
    <plugin name="cordova.plugins.diagnostic" spec="^4.0.10" />
    <plugin name="cordova-plugin-nativeaudio" spec="^3.0.9" />
    <plugin name="cordova-plugin-bluetooth-serial" spec="^0.4.7" />
    <plugin name="cordova-plugin-autostart" spec="https://github.com/ToniKorin/cordova-plugin-autostart.git" />
    <plugin name="cordova-plugin-background-mode" spec="https://github.com/katzer/cordova-plugin-background-mode.git" />
    <plugin name="cordova-plugin-device" spec="^2.0.2" />
    <plugin name="cordova-plugin-ionic" spec="^5.2.6">
        <variable name="APP_ID" value="*****" />
        <variable name="CHANNEL_NAME" value="Production" />
        <variable name="UPDATE_METHOD" value="none" />
        <variable name="UPDATE_API" value="https://api.ionicjs.com" />
        <variable name="MAX_STORE" value="2" />
        <variable name="MIN_BACKGROUND_DURATION" value="30" />
    </plugin>
    <engine name="android" spec="6.4.0" />
</widget>

`

**Comment by jcesarmobile** [comment]
Looks like there were some npm issues yesterday, can you test again?

Also, we released 5.2.7 version, can you try with that one? (well, as you have ^5.2.6 in both config.xml and package.json it should pick 5.2.7, so rebuilding should be enough)

**Comment by ChampRay** [comment]
Just ran the test and updated the plugin to 5.2.7, still have the same issue.

**Comment by ChampRay** [comment]
Just ran the package build again and updated plugins to 5.2.7

Still ran into the same issue.

**Comment by nphyatt** [comment]
@ChampRay can you [open a support ticket](https://ionic.zendesk.com/hc/en-us/requests/new) and ask them to direct it to me? You can refer to this issue. Seems like it may be more of an issue with Ionic Package and it’ll be easier to look into the logs etc. if I have your account info.

**Comment by ChampRay** [comment]
@nphyatt Okay, my ticket #18437

**Comment by nphyatt** [comment]
Sounds like support helped you solve the issue. Closing.
