### ISSUE TITLE
Android: 3.0.0 deploy.redirect() fails on manual update

### ISSUE THREAD

**Issue by ivinogradov** [ionic-team/cordova-plugin-ionic#50]
**Description:**
Working with `cordova-plugin-ionic@3.0.0` and doing live updates manually, `deploy.redirect()` doesn't load new snapshot on Android (it works fine on iOS). I have to restart my app in order for the update to kick in.

**Steps to Reproduce:**
1. Install the latest plugin with UPDATE_METHOD="none"
2. Manually initialize the plugin, check, download, and extract the update.
3. The extract count goes only to 86%, after which the plugin claims that it removed the snapshot.
4. "Attempted to send a second callback for ID: IonicDeploy" error is displayed
5. The app doesn't update until you restart it

**Output:**

    01-26 10:52:01.939 5510-5553/com.test.myapp I/IONIC.DEPLOY.EXTRACT: Progress: 86%
    01-26 10:52:01.999 5510-5553/com.test.myapp I/IONIC.DEPLOY.REMOVE: Removed www.zip
    01-26 10:52:01.999 5510-5553/com.test.myapp W/CordovaPlugin: Attempted to send a second callback for ID: IonicDeploy1991571862
                                                                              Result was: "done"

**My `ionic info`:**

    [WARN] Error with ./www/lib/ionic/version.json file: FILE_NOT_FOUND, trying ./bower.json.

(I have Ionic 1.3.0 bower package, which doesn't have `version.json`.)

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    Cordova Platforms : android 6.2.3 ios 4.5.4
    Ionic Framework   : unknown

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2
    ios-sim           : 5.0.13
    Node              : v9.3.0
    npm               : 3.10.10
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Users/ilyavinogradov/Library/Android/sdk

Misc:

    backend : pro

**Other Information (`cordova plugin`):** 

    com.hutchind.cordova.plugins.streamingmedia 0.1.4 "StreamingMedia"
    com.megster.cordova.FileChooser 0.0.0 "File Chooser"
    com.ohh2ahh.plugins.appavailability 0.3.1 "AppAvailability"
    com.ququplay.websocket.WebSocket 0.1.0 "WebSocket"
    org.transistorsoft.cordova.background-geolocation 0.3.6 "CDVBackgroundGeoLocation"
    cordova-fabric-plugin 1.1.9 "cordova-fabric-plugin"
    cordova-plugin-add-swift-support 1.7.1 "AddSwiftSupport"
    cordova-plugin-app-event 1.2.0 "Application Events"
    cordova-plugin-app-version 0.1.8 "AppVersion"
    cordova-plugin-appavailability 0.4.2 "AppAvailability"
    cordova-plugin-badge 0.8.6 "Badge"
    cordova-plugin-camera 2.4.1 "Camera"
    cordova-plugin-compat 1.1.0 "Compat"
    cordova-plugin-customurlscheme 4.2.0 "Custom URL scheme"
    cordova-plugin-device 1.1.1 "Device"
    cordova-plugin-dialogs 1.2.1 "Notification"
    cordova-plugin-file 4.1.1 "File"
    cordova-plugin-geolocation 2.1.0 "Geolocation"
    cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
    cordova-plugin-ionic 3.0.0 "IonicCordova"
    cordova-plugin-ios-disableshaketoedit 1.0.0 "iOS Disable Shake to Edit"
    cordova-plugin-splashscreen 5.0.1 "Splashscreen"
    cordova-plugin-statusbar 2.1.1 "StatusBar"
    cordova-plugin-whitelist 1.2.1 "Whitelist"
    de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
    ionic-plugin-keyboard 1.0.8 "Keyboard"
    org.transistorsoft.cordova.background-geolocation 0.3.6 "CDVBackgroundGeoLocation"
    org.unasus.usablespace 1.0.1 "UsableSpace"
    phonegap-plugin-push 1.6.0 "PushPlugin"

**Comment by Fuiste** [comment]
This should be fixed in version 3.1.0 of the plugin, which was just released.

**Comment by ivinogradov** [comment]
@Fuiste  The issue still happens even on version 3.1.1 of the plugin (though there is no callback error like it used to be):
```
02-07 19:08:52.330 16174-16234/com.test.myapp I/IONIC.DEPLOY.EXTRACT: Progress: 85%
02-07 19:08:52.350 16174-16234/com.test.myapp I/IONIC.DEPLOY.EXTRACT: Progress: 85%
02-07 19:08:52.350 16174-16174/com.test.myapp W/BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 16174
02-07 19:08:52.360 16174-16234/com.test.myapp I/IONIC.DEPLOY.EXTRACT: Progress: 85%
02-07 19:08:52.360 16174-16234/com.test.myapp I/IONIC.DEPLOY.EXTRACT: Progress: 85%
02-07 19:08:52.360 16174-16234/com.test.myapp I/IONIC.DEPLOY.EXTRACT: Progress: 86%
02-07 19:08:52.370 16174-16234/com.test.myapp I/IONIC.DEPLOY.EXTRACT: Progress: 86%
02-07 19:08:52.370 16174-16234/com.test.myapp I/IONIC.DEPLOY.EXTRACT: Progress: 86%
02-07 19:08:52.370 16174-16234/com.test.myapp I/IONIC.DEPLOY.EXTRACT: Progress: 86%
02-07 19:08:52.370 16174-16234/com.test.myapp I/IONIC.DEPLOY.EXTRACT: Progress: 86%
02-07 19:08:52.380 16174-16234/com.test.myapp I/IONIC.DEPLOY.EXTRACT: Progress: 86%
02-07 19:08:52.380 16174-16234/com.test.myapp I/IONIC.DEPLOY.EXTRACT: Progress: 86%
02-07 19:08:52.380 16174-16234/com.test.myapp I/IONIC.DEPLOY.EXTRACT: Progress: 86%
02-07 19:08:52.390 16174-16234/com.test.myapp I/IONIC.DEPLOY.EXTRACT: Progress: 86%
02-07 19:08:52.390 16174-16234/com.test.myapp I/IONIC.DEPLOY.EXTRACT: Progress: 86%
02-07 19:08:52.440 16174-16234/com.test.myapp I/IONIC.DEPLOY.REMOVE: Removed www.zip
02-07 19:08:53.121 16174-16174/com.test.myapp W/BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 16174
```

As you can see it stops at 86%, and saying it removed zip archive. If I kill and re-launch the app, then the snapshot is applied (so it wasn't removed like the plugin claimed.)

Here is my updated `cordova plugins`:
```
com.hutchind.cordova.plugins.streamingmedia 0.1.4 "StreamingMedia"
com.megster.cordova.FileChooser 0.0.0 "File Chooser"
com.ohh2ahh.plugins.appavailability 0.3.1 "AppAvailability"
com.ququplay.websocket.WebSocket 0.1.0 "WebSocket"
org.transistorsoft.cordova.background-geolocation 0.3.6 "CDVBackgroundGeoLocation"
cordova-fabric-plugin 1.1.9 "cordova-fabric-plugin"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-app-version 0.1.8 "AppVersion"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-customurlscheme 4.2.0 "Custom URL scheme"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-ionic 3.1.1 "IonicCordova"
cordova-plugin-ios-disableshaketoedit 1.0.0 "iOS Disable Shake to Edit"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.1.1 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
ionic-plugin-keyboard 1.0.8 "Keyboard"
org.transistorsoft.cordova.background-geolocation 0.3.6 "CDVBackgroundGeoLocation"
org.unasus.usablespace 1.0.1 "UsableSpace"
phonegap-plugin-push 1.6.0 "PushPlugin"
```

**Comment by ivinogradov** [comment]
@Fuiste The behavior I described is caused by issue #59. I was always listening for "done" from extract callback, but Android actually returns "true" upon extraction finish. 

So I changed my extract callback logic to check for both, and it fixed the issue:
```
      /* @param {String or Number} extractEvent number representing percent of completion,
       *  or string 'done' (iOS) or 'true' (Android) if extraction has finished */
        if(extractEvent === 'done' || extractEvent === 'true') { // https://github.com/ionic-team/cordova-plugin-ionic/issues/59
          onIonicExtractSuccess();
        } else {
           setExtractProgress(extractEvent);
        }
```

**Comment by Fuiste** [comment]
Yeah, this was a regression I introduced when I removed the wrong callback in 3.1.1.

Should be cleared up in 3.1.2, sorry for the headache there.
