### ISSUE TITLE
ERROR: the cordova-plugin-ionic plugin is not installed. Install it for better device information for runtime errors.

### ISSUE THREAD

**Issue by fierysolid** [ionic-team/cordova-plugin-ionic#6]
The plugin is definitely installed, but throws this error whenever I run it. Would love to get moved over to the Ionic Pro deploys, but as of right now I can't so I hope the kinks with this get worked out before January.

**Comment by mlynch** [comment]
Thanks for the issue, looking into now

**Comment by fierysolid** [comment]
@mlynch let me know if you need anything from me. I have added/removed the plugin, removed everything and tried `cordova prepare` and every time I still get a `plugin_not_installed`

**Comment by mlynch** [comment]
Will do. Anyways this isn’t a fatal error as the plugin isn’t necessary for monitoring. Regardless we will get this fixed

**Comment by fierysolid** [comment]
I actually use it for the Live Deploys, so it may be related to the plugin trying to run to get a new build.

**Comment by JeremyLopez** [comment]
I have a very similar issue.  Also, my Pro Deploy will not work and I assume it's related to this.

**Comment by mlynch** [comment]
Looking into another issue that might be related, but this shouldn't impact deploy. Still investigating

**Comment by mlynch** [comment]
Can y'all try @ionic/pro version 1.0.10?

**Comment by JeremyLopez** [comment]
I still see:

`ionic-pro.min.js:1 the cordova-plugin-ionic plugin is not installed. Install it for better device information for runtime errors.`

**Comment by PeterLessels** [comment]
Same:
the cordova-plugin-ionic plugin is not installed. Install it for better device information for runtime errors.
@ionic/pro version 1.0.10

**Comment by mlynch** [comment]
Okay, try 1.0.11. Again, this error is meaningless, it doesn't indicate any kind of problem

For those using the CDN version, I'll be updating that shortly, but would recommend moving to npm if you can.

**Comment by PeterLessels** [comment]
Was already on npm. Upgrade to 1.0.11. Issue now fixed for ionic serve.

For ionic build, there is no cordova.js in root of www. So when I serve it as a wep app, there is a 404 on cordova.js and then this error.

Peter

**Comment by mlynch** [comment]
@PeterLessels that's fine, cordova.js won't exist on the web. If you want to avoid that issue you can remove `cordova.js` from the script includes. We're going to make this more automatic in the future.

**Comment by fierysolid** [comment]
Has anyone tried using Ionic Deploy with Ionic Pro using the latest update? If not I'll report back with findings in the next week.

**Comment by fierysolid** [comment]
Was this error message fixed in 2.x?

**Comment by JorisDebonnet** [comment]
I am on cordova-plugin-ionic 2.0.3, but still get the error during a `ionic serve`. I know it's not a fatal error, but if no Cordova is detected, then this should be a warning (if anything), not an error. 

Can this be reopened until that is fixed please?

**Comment by JorisDebonnet** [comment]
Here are some (unrelated) plugin warnings that are more 'sensible' (because they're warnings). Perhaps this one can be changed a bit in a similar sense?
> Native: tried calling StatusBar.styleLightContent, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
> Native: tried calling Splashscreen.hide, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator

**Comment by marcochavezf** [comment]
I had the same problem with the plugin installed in Ionic v1. I moved `Pro.init` inside of `$ionicPlatform.ready` and the problem was fixed.
